title: Kathleen Chartier # your name (or website title) here
logo: "/images/KFCpic.png?raw=true" # your photo (or logo) here
description: Data Analyst
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have professional experience as an engineer and mathematics educator.  I am very<br>
  curious about the world around me and am frequently asking "How?" or "Why?".<br>
  That is why I love data analytics so much - it helps me to answer those questions!
  
  <br><br>
  <a href="https://www.linkedin.com/in/kathleen-chartier-338546254">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
