title: Kathleen Chartier # your name (or website title) here
logo: "/images/KFCpic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst<br>
  I have professional experience as an engineer and mathematics educator and have
  recently become a Data Analyst and I am excited.  I am very curious about the world
  around me and am frequently asking "How?" or "Why?".  That is why I love data analytics
  so much - it helps me to answer those questions!
  <br>
  <a href="https://www.linkedin.com/in/kathleen-chartier-338546254">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/kathleenfchartier">View My GitHub Repository</a> 
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
